coverage:
  status:
    project:
      default:
        target: 83.33%
    patch:
      default:
        target: 75%

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: proj-
        type: project
        target: 75%
        threshold: 1%
      - name_prefix: patch-
        type: patch
        target: 90%
comment:
  after_n_builds: 1
  layout: "reach, diff, files"
  require_head: true
  require_changes: false
ignore:
  - 'src/tests'
